[Bot]
Key = false
# ├ Укажите ключ в формате Key = "ваш_ключ" или оставьте false, чтобы код был взят из файла key в папке C:/MichiPythonFiles/GreenTeaBot/
# └ Specify the key in the format Key = "your_key" or leave false so that the code is taken from the key file in the folder C:/MichiPythonFiles/GreenTeaBot/
ID = -1002622534151
# ├ Укажите ID своего чата, откуда бы бот брал сообщения и общался
# └ Specify your chat ID, from where the bot would receive messages and communicate
BotUsername = "TT_GrenTeaBot"
# ├ Тег вашего бота
# └ Your bot's tag
Random = 0.15
# ├ Укажите число от 0.0 до 1.0 - это будет шанс от 0% до 100% на ответ на сообщения
# └ Specify a number from 0.0 to 1.0 - this will be a 0% to 100% chance of responding to messages

[Ollama]
Model = "gpt-oss:20b"
# ├ Укажите используемую модель ИИ (она должна быть установлена в заранее)
# └ pecify the AI model used (it must be installed in advance)
CPU = false
# ├ Сколько потоков процессора будет использовано
# └ How many CPU threads will be used
Prompt = "GTB-Prompt-8b-RU"
# ├ Выберите один из промптов в папке prompts или создайте свой (подробнее в readme.txt)
# └ Select one of the prompts in the prompts folder or create your own (for more information, see readme.txt)
History = 5
# ├ Сколько сообщений будет запоминать бот для контекста
# └ How many messages will the bot remember for context

[Script]
Logs = true
# ├ Включает логирование действий
# └ Enables logging of actions

[Translation]
Translate = false
# ├ Включает переводчик по системе 'Выбранный язык'->'Английский'(так как ИИ обучены в основном на нём)->'Выбранный язык' (полезно для работы с маленькими моделями, так как куда больше англоязычных моделей под 1b и их проще переводить таким образом)
# └ Enables the translator on the system 'Selected language'->'English'(since AI is mainly trained on it)->'Selected language' (useful for working with small models, as there are many more English-language models for 1b and they are easier to translate this way)
Engien = "Google"
# └ Google|DeepL|Amazon|ModernMT|LibreTranslate
UserLanguage = "ru"
# ├ Какой именно язык будет выбран, если параметр сверху истина ('true')
# └ Which language will be selected if the upper parameter is 'true'